// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_MENU_MAIN_H
#define UI_MENU_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_menu_main
extern void ui_menu_main_screen_init(void);
extern void ui_menu_main_screen_destroy(void);
extern void ui_main_menu_event(lv_event_t * e);
extern lv_group_t * ui_menu_main_group;
extern lv_obj_t * ui_menu_main_title;
extern lv_obj_t * ui_menu_main_title_label;
extern lv_obj_t * ui_real_data_button;
extern lv_obj_t * ui_real_data_label;
extern lv_obj_t * ui_event_record_button;
extern lv_obj_t * ui_event_record_label;
extern lv_obj_t * ui_dz_param_button;
extern lv_obj_t * ui_dz_param_label;
extern lv_obj_t * ui_com_param_button;
extern lv_obj_t * ui_com_param_label;
extern lv_obj_t * ui_sys_maint_button;
extern lv_obj_t * ui_sys_maint_label;
extern lv_obj_t * ui_clock_set_button;
extern lv_obj_t * ui_clock_set_label;
extern lv_obj_t * ui_dev_manage_button;
extern lv_obj_t * ui_dev_manage_label;
extern lv_obj_t * ui_FA_state_button;
extern lv_obj_t * ui_FA_state_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

