// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "../../ui.h"
#include "../../my_file/display_init.h"
lv_group_t * ui_menu_main_group = NULL;
lv_obj_t * ui_menu_main_title = NULL;
lv_obj_t * ui_menu_main_title_label = NULL;
lv_obj_t * ui_real_data_button = NULL;
lv_obj_t * ui_real_data_label = NULL;
lv_obj_t * ui_event_record_button = NULL;
lv_obj_t * ui_event_record_label= NULL;
lv_obj_t * ui_dz_param_button = NULL;
lv_obj_t * ui_dz_param_label = NULL;
lv_obj_t * ui_com_param_button = NULL;
lv_obj_t * ui_com_param_label = NULL;
lv_obj_t * ui_sys_maint_button = NULL;
lv_obj_t * ui_sys_maint_label= NULL;
lv_obj_t * ui_clock_set_button = NULL;
lv_obj_t * ui_clock_set_label = NULL;
lv_obj_t * ui_dev_manage_button = NULL;
lv_obj_t * ui_dev_manage_label= NULL;
lv_obj_t * ui_FA_state_button = NULL;
lv_obj_t * ui_FA_state_label = NULL;

extern lv_style_t style_option_unselected;
extern lv_style_t style_option_selected;
extern lv_style_t style_title;

// event funtions
void ui_main_menu_event(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_obj_t * btn = lv_event_get_target(e);    // 获取事件目标对象（按钮）
    if(btn == NULL) return;
    lv_obj_t * label = (lv_obj_t *)lv_obj_get_user_data(btn);// 从按钮的user_data中取出标签句柄
    if(label == NULL) return;
    lv_group_t *group = lv_obj_get_group(btn);  // 获取按钮所属的组
    if(group == NULL) return;

    lv_indev_t *indev = lv_win32_keypad_device_object;
    if(indev == NULL) return;

    uint32_t key;
    switch(event_code)
    {
        case LV_EVENT_FOCUSED:      // 如果事件是获得焦点
            lv_obj_remove_style(label, &style_option_unselected, 0);
            lv_obj_add_style(label, &style_option_selected, 0);
            break;
        case LV_EVENT_DEFOCUSED:    // 如果事件是失去焦点
            lv_obj_remove_style(label, &style_option_selected, 0);
            lv_obj_add_style(label, &style_option_unselected, 0);
            break;
        case LV_EVENT_KEY:
            key = lv_indev_get_key(indev);
            switch(key)
            {
                case LV_KEY_ENTER:
                    if (btn == ui_real_data_button)
                    {
                        lv_indev_set_group(indev,ui_real_data_group);// 取消输入设备与对象组的关联，防止在动画过程中输入设备操作引起的异常
                        _ui_screen_change(&ui_real_data_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_real_data_screen_init);// 切换到实时数据界面，使用淡入动画，动画持续500ms，无延迟
                    }
                    if (btn == ui_dev_manage_button)
                    {
                        lv_indev_set_group(indev,ui_dev_manage_group);
                        _ui_screen_change(&ui_dev_manage_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dev_manage_screen_init);
                    }
                    if (btn == ui_dz_param_button)
                    {
                        lv_indev_set_group(indev,ui_dz_param_group);
                        _ui_screen_change(&ui_dz_param_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dz_param_screen_init);
                    }
                    if (btn == ui_com_param_button)
                    {
                        lv_indev_set_group(indev,ui_com_param_group);
                        _ui_screen_change(&ui_com_param_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_com_param_screen_init);
                    }
                    if (btn == ui_event_record_button)
                    {
                        lv_indev_set_group(indev,ui_event_record_group);
                        _ui_screen_change(&ui_event_record_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_event_record_screen_init);
                    }
                    if (btn == ui_clock_set_button)
                    {
                        lv_indev_set_group(indev, ui_clock_set_group);
                        _ui_screen_change(&ui_clock_set_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_clock_set_screen_init);
                    }
                    if (btn == ui_FA_state_button)
                    {
                        lv_indev_set_group(indev, ui_FA_state_group);
                        _ui_screen_change(&ui_FA_state_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_FA_state_screen_init);
                    }
                    if (btn == ui_sys_maint_button)
                    {
                        lv_indev_set_group(indev, ui_sys_maint_group);
                        _ui_screen_change(&ui_sys_maint_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_sys_maint_screen_init);
                    }
                    break;
                case LV_KEY_UP:
                    if(group != NULL && ui_display.edit_state == UNEDIT_STATE) {
                        lv_group_focus_prev(group);
                    }
                    break;
                case LV_KEY_DOWN:
                    if(group != NULL && ui_display.edit_state == UNEDIT_STATE) {
                        lv_group_focus_next(group);
                    }
                    break;
                default:
                    break;
            }
        default:
            break;
    }
}

// build funtions
void ui_menu_main_screen_init(void)
{
    ui_menu_main_title = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_menu_main_title, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menu_main_group = lv_group_create(); // 创建一个新的对象组
    lv_indev_t *indev = lv_win32_keypad_device_object;// 获取输入设备对象

    ui_menu_main_title_label = lv_label_create(ui_menu_main_title);
    lv_obj_set_width(ui_menu_main_title_label, lv_pct(100));
    lv_obj_set_height(ui_menu_main_title_label, LV_SIZE_CONTENT);    /// 16
    lv_label_set_text(ui_menu_main_title_label, "主菜单");
    lv_obj_set_align(ui_menu_main_title_label, LV_ALIGN_TOP_MID);
    lv_obj_add_style(ui_menu_main_title_label, &style_title, 0);

    /*-----创建实时数据菜单项-----*/
    ui_real_data_button = lv_btn_create(ui_menu_main_title);
    lv_obj_set_button_init(ui_real_data_button, lv_pct(100), 20);
    lv_obj_align_to(ui_real_data_button, ui_menu_main_title_label, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_real_data_label = lv_label_create(ui_real_data_button);
    lv_obj_set_label_init(ui_real_data_label, "实时数据", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_real_data_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_real_data_button, ui_real_data_label);// 将标签句柄存储到按钮的user_data中，方便事件回调中访问
    lv_obj_add_event_cb(ui_real_data_button, ui_main_menu_event, LV_EVENT_ALL, NULL);

    /*-----创建事件记录菜单项-----*/
    ui_event_record_button = lv_btn_create(ui_menu_main_title);
    lv_obj_set_button_init(ui_event_record_button, lv_pct(100), 20);
    lv_obj_align_to(ui_event_record_button, ui_real_data_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_event_record_label = lv_label_create(ui_event_record_button);
    lv_obj_set_label_init(ui_event_record_label, "事件记录", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_event_record_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_event_record_button, ui_event_record_label);
    lv_obj_add_event_cb(ui_event_record_button, ui_main_menu_event, LV_EVENT_ALL, NULL);

    /*-----创建定值参数菜单项-----*/
    ui_dz_param_button = lv_btn_create(ui_menu_main_title);
    lv_obj_set_button_init(ui_dz_param_button, lv_pct(100), 20);
    lv_obj_align_to(ui_dz_param_button, ui_event_record_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_dz_param_label = lv_label_create(ui_dz_param_button);
    lv_obj_set_label_init(ui_dz_param_label, "定值参数", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_dz_param_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_dz_param_button, ui_dz_param_label);
    lv_obj_add_event_cb(ui_dz_param_button, ui_main_menu_event, LV_EVENT_ALL, NULL);


    /*-----创建通讯参数菜单项-----*/
    ui_com_param_button = lv_btn_create(ui_menu_main_title);
    lv_obj_set_button_init(ui_com_param_button, lv_pct(100), 20);
    lv_obj_align_to(ui_com_param_button, ui_dz_param_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_com_param_label = lv_label_create(ui_com_param_button);
    lv_obj_set_label_init(ui_com_param_label, "通讯参数", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_com_param_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_com_param_button, ui_com_param_label);
    lv_obj_add_event_cb(ui_com_param_button, ui_main_menu_event, LV_EVENT_ALL, NULL);


    /*-----创建系统维护菜单项-----*/
    ui_sys_maint_button = lv_btn_create(ui_menu_main_title);
    lv_obj_set_button_init(ui_sys_maint_button, lv_pct(100), 20);
    lv_obj_align_to(ui_sys_maint_button, ui_com_param_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_sys_maint_label = lv_label_create(ui_sys_maint_button);
    lv_obj_set_label_init(ui_sys_maint_label, "系统维护", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_sys_maint_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_sys_maint_button, ui_sys_maint_label);
    lv_obj_add_event_cb(ui_sys_maint_button, ui_main_menu_event, LV_EVENT_ALL, NULL);


    /*-----创建时钟设置菜单项-----*/
    ui_clock_set_button = lv_btn_create(ui_menu_main_title);
    lv_obj_set_button_init(ui_clock_set_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_button, ui_sys_maint_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_label = lv_label_create(ui_clock_set_button);
    lv_obj_set_label_init(ui_clock_set_label, "时钟设置", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_button, ui_clock_set_label);
    lv_obj_add_event_cb(ui_clock_set_button, ui_main_menu_event, LV_EVENT_ALL, NULL);


    /*-----创建装置管理菜单项-----*/
    ui_dev_manage_button = lv_btn_create(ui_menu_main_title);
    lv_obj_set_button_init(ui_dev_manage_button, lv_pct(100), 20);
    lv_obj_align_to(ui_dev_manage_button, ui_clock_set_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_dev_manage_label = lv_label_create(ui_dev_manage_button);
    lv_obj_set_label_init(ui_dev_manage_label, "装置管理", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_dev_manage_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_dev_manage_button, ui_dev_manage_label);
    lv_obj_add_event_cb(ui_dev_manage_button, ui_main_menu_event, LV_EVENT_ALL, NULL);


    /*-----创建FA状态菜单项-----*/
    ui_FA_state_button = lv_btn_create(ui_menu_main_title);
    lv_obj_set_button_init(ui_FA_state_button, lv_pct(100), 20);
    lv_obj_align_to(ui_FA_state_button, ui_dev_manage_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_FA_state_label = lv_label_create(ui_FA_state_button);
    lv_obj_set_label_init(ui_FA_state_label, "FA 状态", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_FA_state_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_FA_state_button, ui_FA_state_label);
    lv_obj_add_event_cb(ui_FA_state_button, ui_main_menu_event, LV_EVENT_ALL, NULL);

    // 将按钮添加到对象组中，使其可被输入设备导航
    lv_group_add_obj(ui_menu_main_group, ui_real_data_button);
    lv_group_add_obj(ui_menu_main_group, ui_event_record_button);
    lv_group_add_obj(ui_menu_main_group, ui_dz_param_button);
    lv_group_add_obj(ui_menu_main_group, ui_com_param_button);
    lv_group_add_obj(ui_menu_main_group, ui_sys_maint_button);
    lv_group_add_obj(ui_menu_main_group, ui_clock_set_button);
    lv_group_add_obj(ui_menu_main_group, ui_dev_manage_button);
    lv_group_add_obj(ui_menu_main_group, ui_FA_state_button);

    lv_indev_set_group(indev, ui_menu_main_group); // 将输入设备与对象组关联

    lv_group_focus_obj(ui_real_data_button);// 默认聚焦第一个按钮
}

void ui_menu_main_screen_destroy(void)
{
    if(ui_menu_main_title) lv_obj_del(ui_menu_main_title);

    // NULL screen variables
    ui_menu_main_title = NULL;
    ui_menu_main_title_label = NULL;
    ui_real_data_button = NULL;
    ui_real_data_label = NULL;
    ui_event_record_button = NULL;
    ui_event_record_label= NULL;
    ui_dz_param_button = NULL;
    ui_dz_param_label = NULL;
    ui_com_param_button = NULL;
    ui_com_param_label = NULL;
    ui_sys_maint_button = NULL;
    ui_sys_maint_label= NULL;
    ui_clock_set_button = NULL;
    ui_clock_set_label = NULL;
    ui_dev_manage_button = NULL;
    ui_dev_manage_label= NULL;
    ui_FA_state_button = NULL;
    ui_FA_state_label = NULL;
}
