// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "../../ui.h"

lv_group_t * ui_password_check_group = NULL;
lv_obj_t * ui_password_check_title = NULL;
lv_obj_t * ui_password_check_title_container = NULL;
lv_obj_t * ui_password_check_title_label = NULL;
lv_obj_t * ui_password_check_input_label[4];
lv_obj_t * ui_password_check_login_button = NULL;
lv_obj_t * ui_password_check_login_label = NULL;
login_status_t login_status = LOGIN_UNSET;
ui_password_check_menu_t ui_password_check_menu = UI_NONE;

static char password[5] = "1234";
static char password_temp[5] = "0000";
static char password_check_temp[2] = {0};
static int password_check_edit_idx = 0;

extern lv_style_t style_option_unselected;
extern lv_style_t style_option_selected;
extern lv_style_t style_title;

const char *get_password(void)
{
    return password;
}

const char *get_password_temp(void)
{
    return password_temp;
}

// event funtions
void ui_password_check_event(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_obj_t * btn = lv_event_get_target(e);    // 获取事件目标对象（按钮）
    lv_obj_t * label = (lv_obj_t *)lv_obj_get_user_data(btn);// 从按钮的user_data中取出标签句柄
    if(label == NULL) return;

    lv_indev_t *indev = lv_win32_keypad_device_object;
    if(indev == NULL) return;

    uint32_t key;
    switch(event_code)
    {
        case LV_EVENT_KEY:
            key = lv_indev_get_key(indev);
            switch(key)
            {
                case LV_KEY_ENTER:
                    if (password_check_edit_idx >= 4)
                    {
                        password_temp[4] = '\0';
                        if (strcmp(password_temp, password) == 0)
                        {
                            memset(password_temp, 0, sizeof(password_temp));
                            login_status = LOGIN_SUCCESS;
                            switch (ui_password_check_menu)
                            {
                                case UI_CLOCK_SET:
                                    ui_password_check_menu = UI_NONE;
                                    password_check_edit_idx = 0;
                                    lv_indev_set_group(indev, ui_clock_set_group);
                                    _ui_screen_change(&ui_clock_set_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_clock_set_screen_init);
                                    break;
                                default:
                                    break;
                            }
                        }else
                        {
                            printf("password error\n");
                        }
                    }
                    break;
                case LV_KEY_BACKSPACE:
                    switch (ui_password_check_menu)
                    {
                        case UI_CLOCK_SET:
                            ui_password_check_menu = UI_NONE;
                            lv_indev_set_group(indev, ui_clock_set_group);
                            _ui_screen_change(&ui_clock_set_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_clock_set_screen_init);
                        break;
                    default:
                        break;
                    }
                case LV_KEY_UP:
                    if (password_check_edit_idx >= 4) break;
                    password_temp[password_check_edit_idx]++;
                    if (password_temp[password_check_edit_idx] > '9') password_temp[password_check_edit_idx] = '0';
                    sprintf(password_check_temp, "%c", password_temp[password_check_edit_idx]);
                    lv_label_set_text(ui_password_check_input_label[password_check_edit_idx], password_check_temp);
                    break;
                case LV_KEY_DOWN:
                    if (password_check_edit_idx >= 4) break;
                    password_temp[password_check_edit_idx]--;
                    if (password_temp[password_check_edit_idx] < '0') password_temp[password_check_edit_idx] = '9';
                    sprintf(password_check_temp, "%c", password_temp[password_check_edit_idx]);
                    lv_label_set_text(ui_password_check_input_label[password_check_edit_idx], password_check_temp);
                    break;
                case LV_KEY_LEFT:
                    if (password_check_edit_idx == 4)
                    {
                        lv_obj_remove_style(ui_password_check_login_label, &style_option_selected, 0);
                        lv_obj_add_style(ui_password_check_login_label, &style_option_unselected, 0);
                    }else
                    {
                        lv_obj_remove_style(ui_password_check_input_label[password_check_edit_idx], &style_option_selected, 0);
                        lv_obj_add_style(ui_password_check_input_label[password_check_edit_idx], &style_option_unselected, 0);
                    }
                    password_check_edit_idx--;
                    if (password_check_edit_idx < 0) password_check_edit_idx = 0;
                    lv_obj_remove_style(ui_password_check_input_label[password_check_edit_idx], &style_option_unselected, 0);
                    lv_obj_add_style(ui_password_check_input_label[password_check_edit_idx], &style_option_selected, 0);
                    break;
                case LV_KEY_RIGHT:
                    lv_obj_remove_style(ui_password_check_input_label[password_check_edit_idx], &style_option_selected, 0);
                    lv_obj_add_style(ui_password_check_input_label[password_check_edit_idx], &style_option_unselected, 0);
                    password_check_edit_idx++;
                    if (password_check_edit_idx >= 5) password_check_edit_idx = 4;
                    if (password_check_edit_idx == 4)
                    {
                        lv_obj_remove_style(ui_password_check_login_label, &style_option_unselected, 0);
                        lv_obj_add_style(ui_password_check_login_label, &style_option_selected, 0);
                    }else
                    {
                        lv_obj_remove_style(ui_password_check_input_label[password_check_edit_idx], &style_option_unselected, 0);
                        lv_obj_add_style(ui_password_check_input_label[password_check_edit_idx], &style_option_selected, 0);
                    }
                    break;
                default:
                    break;
            }
        default:
            break;
    }
}

// build funtions
void ui_password_check_screen_init(void)
{
    ui_password_check_title = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_password_check_title, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_password_check_group = lv_group_create(); // 创建一个新的对象组
    lv_indev_t *indev = lv_win32_keypad_device_object;

    ui_password_check_title_container = lv_obj_create(ui_password_check_title);
    lv_obj_set_size(ui_password_check_title_container, 100, 100);
    lv_obj_set_align(ui_password_check_title_container, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_opa(ui_password_check_title_container, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_password_check_title_container, 2, 0);
    lv_obj_set_style_border_side(ui_password_check_title_container, LV_BORDER_SIDE_FULL, 0);
    lv_obj_set_style_border_color(ui_password_check_title_container, lv_color_black(), 0);
    lv_obj_set_style_outline_width(ui_password_check_title_container, 0, 0);
    lv_obj_set_style_shadow_width(ui_password_check_title_container, 0, 0);
    lv_obj_set_style_radius(ui_password_check_title_container, 0, 0);
    lv_obj_set_scrollbar_mode(ui_password_check_title_container, LV_SCROLLBAR_MODE_OFF);

    /*-----创建“密码检查”便签-----*/
    ui_password_check_title_label = lv_label_create(ui_password_check_title_container);
    lv_label_set_text(ui_password_check_title_label, "密码密码");
    lv_obj_add_style(ui_password_check_title_label, &style_option_unselected, 0);
    lv_obj_align_to(ui_password_check_title_label, ui_password_check_title_container, LV_ALIGN_CENTER, 0, 0);

    // ========== 密码 ==========
    ui_password_check_input_label[0] = lv_label_create(ui_password_check_title_container);
    lv_obj_set_size(ui_password_check_input_label[0], 16, 20);
    lv_obj_add_style(ui_password_check_input_label[0], &style_option_selected, 0);
    lv_obj_align_to(ui_password_check_input_label[0], ui_password_check_title, LV_ALIGN_CENTER, -24, 30);

    ui_password_check_input_label[1] = lv_label_create(ui_password_check_title_container);
    lv_obj_set_size(ui_password_check_input_label[1], 16, 20);
    lv_obj_add_style(ui_password_check_input_label[1], &style_option_unselected, 0);
    lv_obj_align_to(ui_password_check_input_label[1], ui_password_check_title, LV_ALIGN_CENTER, -8, 30);

    ui_password_check_input_label[2] = lv_label_create(ui_password_check_title_container);
    lv_obj_set_size(ui_password_check_input_label[2], 16, 20);
    lv_obj_add_style(ui_password_check_input_label[2], &style_option_unselected, 0);
    lv_obj_align_to(ui_password_check_input_label[2], ui_password_check_title, LV_ALIGN_CENTER, 8, 30);

    ui_password_check_input_label[3] = lv_label_create(ui_password_check_title_container);
    lv_obj_set_size(ui_password_check_input_label[3], 16, 20);
    lv_obj_add_style(ui_password_check_input_label[3], &style_option_unselected, 0);
    lv_obj_align_to(ui_password_check_input_label[3], ui_password_check_title, LV_ALIGN_CENTER, 24, 30);

    for (size_t i = 0; i < sizeof(password) - 1 ; i++)
    {
        sprintf(password_check_temp, "%c", password_temp[i]);
        lv_label_set_text(ui_password_check_input_label[i], password_check_temp);
    }

    /*-----创建登录按键-----*/
    ui_password_check_login_button = lv_btn_create(ui_password_check_title_container);
    lv_obj_set_button_init(ui_password_check_login_button, lv_pct(100), 20);
    lv_obj_align_to(ui_password_check_login_button, ui_password_check_title, LV_ALIGN_CENTER, 0, 60);
    ui_password_check_login_label = lv_label_create(ui_password_check_login_button);
    lv_obj_set_label_init(ui_password_check_login_label, "登录", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_password_check_login_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_password_check_login_button, ui_password_check_login_label);
    lv_obj_add_event_cb(ui_password_check_login_button, ui_password_check_event, LV_EVENT_ALL, NULL);

    // 将按钮添加到对象组中，使其可被输入设备导航
    lv_group_add_obj(ui_password_check_group, ui_password_check_login_button);
    lv_indev_set_group(indev, ui_password_check_group); // 将输入设备与对象组关联
    lv_group_focus_obj(ui_password_check_login_button);
}

void ui_password_check_screen_destroy(void)
{
    if(ui_password_check_title) lv_obj_del(ui_password_check_title);
    // NULL screen variables
    ui_password_check_group = NULL;
    ui_password_check_title_container = NULL;
    ui_password_check_title = NULL;
    ui_password_check_title_label = NULL;
    for(int i = 0; i < 4; i++)
    {
        ui_password_check_input_label[i] = NULL;
    }
    ui_password_check_login_button = NULL;
    ui_password_check_login_label = NULL;
}
