// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_PASSWORD_CHECK_H
#define UI_PASSWORD_CHECK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_password_check
#include "../../my_file/lcd_database.h"

typedef enum {
    LOGIN_UNSET,    //未登录
    LOGIN_SUCCESS,  //登录成功
} login_status_t;

typedef enum {
    UI_NONE = 0,
    UI_CLOCK_SET,
} ui_password_check_menu_t;

extern login_status_t login_status;
extern ui_password_check_menu_t ui_password_check_menu;
const char *get_password(void);
const char *get_password_temp(void);
extern void ui_password_check_event(lv_event_t * e);
extern void ui_password_check_screen_init(void);
extern void ui_password_check_screen_destroy(void);
extern lv_group_t * ui_password_check_group;
extern lv_obj_t * ui_password_check_title;
extern lv_obj_t * ui_password_check_title_container;
extern lv_obj_t * ui_password_check_title_label;
extern lv_obj_t * ui_password_check_input_label[4];
extern lv_obj_t * ui_password_check_login_button;
extern lv_obj_t * ui_password_check_login_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

