// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_POPUP_WINDOW_H
#define UI_POPUP_WINDOW_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_popup_window
extern void ui_popup_window_event(lv_event_t * e);
extern void ui_popup_window_screen_init(void);
extern void ui_popup_window_screen_destroy(void);
extern lv_group_t * ui_popup_window_group;
extern lv_obj_t * ui_popup_window_title;
extern lv_obj_t * ui_popup_window_title_label;
extern lv_obj_t * ui_popup_window_confirm_button;
extern lv_obj_t * ui_popup_window_confirm_label;
extern lv_obj_t * ui_popup_window_cancel_button;
extern lv_obj_t * ui_popup_window_cancel_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

