// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "../../ui.h"
lv_group_t * ui_popup_window_group = NULL;
lv_obj_t * ui_popup_window_title = NULL;
lv_obj_t * ui_popup_window_title_label = NULL;
lv_obj_t * ui_popup_window_confirm_button = NULL;
lv_obj_t * ui_popup_window_confirm_label = NULL;
lv_obj_t * ui_popup_window_cancel_button = NULL;
lv_obj_t * ui_popup_window_cancel_label = NULL;

extern lv_style_t style_option_unselected;
extern lv_style_t style_option_selected;
extern lv_style_t style_title;

// event funtions
void ui_popup_window_event(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_obj_t * btn = lv_event_get_target(e);    // 获取事件目标对象（按钮）
    if(btn == NULL) return;
    lv_obj_t * label = (lv_obj_t *)lv_obj_get_user_data(btn);// 从按钮的user_data中取出标签句柄
    if(label == NULL) return;
    lv_group_t *group = lv_obj_get_group(btn);  // 获取按钮所属的组
    if(group == NULL) return;
    lv_indev_t *indev = lv_win32_keypad_device_object;
    if(indev == NULL) return;

    uint32_t key;
    switch(event_code)
    {
        case LV_EVENT_FOCUSED:          // 如果事件是获得焦点
            lv_obj_remove_style(label, &style_option_unselected, 0);
            lv_obj_add_style(label, &style_option_selected, 0);
            break;
        case LV_EVENT_DEFOCUSED:        // 如果事件是失去焦点
            lv_obj_remove_style(label, &style_option_selected, 0);
            lv_obj_add_style(label, &style_option_unselected, 0);
            break;
        case LV_EVENT_KEY:
            key = lv_indev_get_key(indev);
            switch(key)
            {
                case LV_KEY_ENTER:

                case LV_KEY_BACKSPACE:
                    switch (ui_display.popup_window_menu)
                    {
                        case UI_PASSWORD_CHECK:
                            ui_display.popup_window_menu = UI_NONE;
                            lv_indev_set_group(indev, ui_password_check_group);
                            _ui_screen_change(&ui_password_check_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_password_check_screen_init);
                            break;
                        case UI_PASSWORD:
                            ui_display.popup_window_menu = UI_NONE;
                            lv_indev_set_group(indev, ui_password_group);
                            _ui_screen_change(&ui_password_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_password_screen_init);
                            break;
                        default:
                            break;
                    }
                    break;
                case LV_KEY_LEFT:
                    if(group != NULL && ui_display.edit_state == UNEDIT_STATE) {
                        lv_group_focus_prev(group);
                    }
                    break;
                case LV_KEY_RIGHT:
                    if(group != NULL && ui_display.edit_state == UNEDIT_STATE) {
                        lv_group_focus_next(group);
                    }
                    break;
                case LV_KEY_UP:
                    if(group != NULL && ui_display.edit_state == UNEDIT_STATE) {
                        lv_group_focus_prev(group);
                    }
                    break;
                case LV_KEY_DOWN:
                    if(group != NULL && ui_display.edit_state == UNEDIT_STATE) {
                        lv_group_focus_next(group);
                    }
                    break;
                default:
                    break;
                }
            break;
        default:
            break;
    }
}

// build funtions
void ui_popup_window_screen_init(void)
{
    ui_popup_window_title = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_popup_window_title, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_popup_window_group = lv_group_create(); // 创建一个新的对象组
    lv_indev_t *indev = lv_win32_keypad_device_object;

    /*-----创建标题-----*/
    ui_popup_window_title_label = lv_label_create(ui_popup_window_title);
    lv_label_set_text(ui_popup_window_title_label, "登录密码");
    lv_obj_add_style(ui_popup_window_title_label, &style_option_unselected, 0);
    lv_obj_align_to(ui_popup_window_title_label, ui_popup_window_title, LV_ALIGN_CENTER, 0, -20);

    /*-----创建确认菜单项-----*/
    ui_popup_window_confirm_button = lv_btn_create(ui_popup_window_title);
    lv_obj_set_button_init(ui_popup_window_confirm_button, 32, 20);
    lv_obj_align_to(ui_popup_window_confirm_button, ui_popup_window_title, LV_ALIGN_CENTER, 32, 20);
    ui_popup_window_confirm_label = lv_label_create(ui_popup_window_confirm_button);
    lv_obj_set_label_init(ui_popup_window_confirm_label, "确认", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_popup_window_confirm_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_popup_window_confirm_button, ui_popup_window_confirm_label);
    lv_obj_add_event_cb(ui_popup_window_confirm_button, ui_popup_window_event, LV_EVENT_ALL, NULL);

    /*-----创建取消菜单项-----*/
    ui_popup_window_cancel_button = lv_btn_create(ui_popup_window_title);
    lv_obj_set_button_init(ui_popup_window_cancel_button, 32, 20);
    lv_obj_align_to(ui_popup_window_cancel_button, ui_popup_window_title, LV_ALIGN_CENTER, -32, 20);
    ui_popup_window_cancel_label = lv_label_create(ui_popup_window_cancel_button);
    lv_obj_set_label_init(ui_popup_window_cancel_label, "取消", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_popup_window_cancel_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_popup_window_cancel_button, ui_popup_window_cancel_label);
    lv_obj_add_event_cb(ui_popup_window_cancel_button, ui_popup_window_event, LV_EVENT_ALL, NULL);

    // 将按钮添加到对象组中，使其可被输入设备导航
    lv_group_add_obj(ui_popup_window_group, ui_popup_window_confirm_button);
    lv_group_add_obj(ui_popup_window_group, ui_popup_window_cancel_button);

    lv_indev_set_group(indev, ui_popup_window_group); // 将输入设备与对象组关联

    lv_group_focus_obj(ui_popup_window_cancel_button);
}

void ui_popup_window_screen_destroy(void)
{
    if(ui_popup_window_title) lv_obj_del(ui_popup_window_title);

    // NULL screen variables
    ui_popup_window_title = NULL;
    ui_popup_window_title_label = NULL;
    ui_popup_window_confirm_button = NULL;
    ui_popup_window_confirm_label = NULL;
    ui_popup_window_cancel_button = NULL;
    ui_popup_window_cancel_label = NULL;
}
