// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_COM_PARAM3_H
#define UI_COM_PARAM3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_com_param3
extern void ui_com_param3_event(lv_event_t * e);
extern void ui_com_param3_screen_init(void);
extern void ui_com_param3_screen_destroy(void);
extern lv_group_t * ui_com_param3_group;
extern lv_obj_t * ui_com_param3_title;
extern lv_obj_t * ui_com_param3_title_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

