// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "../../ui.h"
#include "../../my_file/display_init.h"
lv_group_t * ui_com_param3_group = NULL;
lv_obj_t * ui_com_param3_title = NULL;
lv_obj_t * ui_com_param3_title_label = NULL;

extern lv_style_t style_option_unselected;
extern lv_style_t style_option_selected;
extern lv_style_t style_title;

// event funtions
void ui_com_param3_event(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_obj_t * btn = lv_event_get_target(e);    // 获取事件目标对象（按钮）
    if(btn == NULL) return;
    lv_obj_t * label = (lv_obj_t *)lv_obj_get_user_data(btn);// 从按钮的user_data中取出标签句柄
    if(label == NULL) return;
    lv_group_t *group = lv_obj_get_group(btn);  // 获取按钮所属的组
    if(group == NULL) return;

    lv_indev_t *indev = lv_win32_keypad_device_object;
    if(indev == NULL) return;

    uint32_t key;
    switch(event_code)
    {
        case LV_EVENT_FOCUSED:        // 如果事件是获得焦点
            lv_obj_remove_style(label, &style_option_unselected, 0);
            lv_obj_add_style(label, &style_option_selected, 0);
            break;
        case LV_EVENT_DEFOCUSED: // 如果事件是失去焦点
            lv_obj_remove_style(label, &style_option_selected, 0);
            lv_obj_add_style(label, &style_option_unselected, 0);
            break;
        case LV_EVENT_KEY:
            key = lv_indev_get_key(indev);
            switch(key)
            {
                case LV_KEY_ENTER:
                    break;
                case LV_KEY_BACKSPACE:
                    lv_indev_set_group(indev, ui_com_param2_group);
                    _ui_screen_change(&ui_com_param2_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_com_param2_screen_init);
                    break;
                case LV_KEY_UP:
                    if(group != NULL && ui_edit_state == UNEDIT_STATE) {
                        lv_group_focus_prev(group);
                    }
                    break;
                case LV_KEY_DOWN:
                    if(group != NULL && ui_edit_state == UNEDIT_STATE) {
                        lv_group_focus_next(group);
                    }
                    break;
                default:
                    break;
            }
            break;
        default:
            break;
    }
}

// build funtions
void ui_com_param3_screen_init(void)
{
    ui_com_param3_title = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_com_param3_title, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_com_param3_group = lv_group_create(); // 创建一个新的对象组
    lv_indev_t *indev = lv_win32_keypad_device_object;

    ui_com_param3_title_label = lv_label_create(ui_com_param3_title);
    lv_obj_set_width(ui_com_param3_title_label, lv_pct(100));
    lv_obj_set_height(ui_com_param3_title_label, LV_SIZE_CONTENT);    /// 16
    lv_label_set_text(ui_com_param3_title_label, "网口参数");
    lv_obj_set_align(ui_com_param3_title_label, LV_ALIGN_TOP_MID);
    lv_obj_add_style(ui_com_param3_title_label, &style_title, 0);

    // // 将按钮添加到对象组中，使其可被输入设备导航
    // lv_group_add_obj(ui_DO_group, ui_point_DO_button);
    // lv_group_add_obj(ui_DO_group, ui_all_DO_button);

    // lv_indev_set_group(indev, ui_DO_group); // 将输入设备与对象组关联

    // lv_group_focus_obj(ui_point_DO_button);
}

void ui_com_param3_screen_destroy(void)
{
    if(ui_com_param3_title) lv_obj_del(ui_com_param3_title);

    // NULL screen variables
    ui_com_param3_title = NULL;
    ui_com_param3_title_label = NULL;
}
