// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_COM_PARAM2_H
#define UI_COM_PARAM2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_com_param2
extern void ui_com_param_event(lv_event_t * e);
extern void ui_com_param2_screen_init(void);
extern void ui_com_param2_screen_destroy(void);
extern lv_group_t * ui_com_param2_group;
extern lv_obj_t * ui_com_param2_title;
extern lv_obj_t * ui_com_param2_title_label;
extern lv_obj_t * ui_serial_param_button;
extern lv_obj_t * ui_serial_param_label;
extern lv_obj_t * ui_com_param3_button;
extern lv_obj_t * ui_com_param3_label;
extern lv_obj_t * ui_101_param_button;
extern lv_obj_t * ui_101_param_label;
extern lv_obj_t * ui_104_param_button;
extern lv_obj_t * ui_104_param_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

