// // This file was generated by SquareLine Studio
// // SquareLine Studio version: SquareLine Studio 1.6.0
// // LVGL version: 8.3.11
// // Project name: SquareLine_Project_DTU

// #ifndef UI_EVENT_RECORD_H
// #define UI_EVENT_RECORD_H

// #ifdef __cplusplus
// extern "C" {
// #endif

// // SCREEN: ui_event_record
// extern lv_group_t * ui_event_record_group;
// extern void ui_event_record_event(lv_event_t * e);
// extern void ui_event_record_screen_init(void);
// extern void ui_event_record_screen_destroy(void);
// extern lv_group_t * ui_event_record_group;
// extern lv_obj_t * ui_event_record_title;
// extern lv_obj_t * ui_event_record_title_label;
// extern lv_obj_t * ui_SOE_button;
// extern lv_obj_t * ui_SOE_label;
// extern lv_obj_t * ui_fault_record_button;
// extern lv_obj_t * ui_fault_record_label;
// // CUSTOM VARIABLES

// #ifdef __cplusplus
// } /*extern "C"*/
// #endif

// #endif

