// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_COMRUN_PARAM_H
#define UI_COMRUN_PARAM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_comrun_param
extern void ui_comrun_param_event(lv_event_t * e);
extern void ui_comrun_param_screen_init(void);
extern void ui_comrun_param_screen_destroy(void);
extern lv_group_t * ui_comrun_param_group;
extern lv_obj_t * ui_comrun_param_title;
extern lv_obj_t * ui_comrun_param_title_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

