// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "../../ui.h"
#include "../../my_file/display_init.h"
lv_group_t * ui_dz_param_group = NULL;
lv_obj_t * ui_dz_param_title = NULL;
lv_obj_t * ui_dz_param_title_label = NULL;
lv_obj_t * ui_dz_view_button = NULL;
lv_obj_t * ui_dz_view_label = NULL;
lv_obj_t * ui_dz_set_button = NULL;
lv_obj_t * ui_dz_set_label = NULL;

extern dz_mode_t current_dz_mode;
extern lv_style_t style_option_unselected;
extern lv_style_t style_option_selected;
extern lv_style_t style_title;

// event funtions
void ui_dz_param_event(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_obj_t * btn = lv_event_get_target(e);    // 获取事件目标对象（按钮）
    lv_obj_t * label = (lv_obj_t *)lv_obj_get_user_data(btn);// 从按钮的user_data中取出标签句柄
    if(label == NULL) return;

    lv_indev_t *indev = lv_win32_keypad_device_object;
    if(indev == NULL) return;

    uint32_t key;
    switch(event_code)
    {
        case LV_EVENT_FOCUSED:        // 如果事件是获得焦点
            lv_obj_remove_style(label, &style_option_unselected, 0);
            lv_obj_add_style(label, &style_option_selected, 0);
            break;
        case LV_EVENT_DEFOCUSED: // 如果事件是失去焦点
            lv_obj_remove_style(label, &style_option_selected, 0);
            lv_obj_add_style(label, &style_option_unselected, 0);
            break;
        case LV_EVENT_KEY:
            key = lv_indev_get_key(indev);
            switch(key)
            {
                case LV_KEY_ENTER:
                    if (btn == ui_dz_view_button)
                    {
                        current_dz_mode = DZ_VIEW_MODE;
                        ui_dz_set_screen_init();
                        lv_indev_set_group(indev, ui_dz_set_group);
                        _ui_screen_change(&ui_dz_set_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dz_set_screen_init);
                    }
                    if (btn == ui_dz_set_button)
                    {
                        current_dz_mode = DZ_SET_MODE;
                        ui_dz_set_screen_init();
                        lv_indev_set_group(indev, ui_dz_set_group);
                        _ui_screen_change(&ui_dz_set_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dz_set_screen_init);
                    }
                    break;
                case LV_KEY_BACKSPACE:
                    lv_indev_set_group(indev, ui_menu_main_group);
                    _ui_screen_change(&ui_menu_main_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_menu_main_screen_init);
                    break;
                default:
                    break;
                }
            break;
        default:
            break;
    }
}

// build funtions
void ui_dz_param_screen_init(void)
{
    ui_dz_param_title = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dz_param_title, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dz_param_group = lv_group_create(); // 创建一个新的对象组
    lv_indev_t *indev = lv_win32_keypad_device_object;

    ui_dz_param_title_label = lv_label_create(ui_dz_param_title);
    lv_obj_set_width(ui_dz_param_title_label, lv_pct(100));
    lv_obj_set_height(ui_dz_param_title_label, LV_SIZE_CONTENT);    /// 16
    lv_label_set_text(ui_dz_param_title_label, "定值参数");
    lv_obj_set_align(ui_dz_param_title_label, LV_ALIGN_TOP_MID);
    lv_obj_add_style(ui_dz_param_title_label, &style_title, 0);


    /*-----创建定值查看菜单项-----*/
    ui_dz_view_button = lv_btn_create(ui_dz_param_title);
    lv_obj_set_button_init(ui_dz_view_button, lv_pct(100), 20);
    lv_obj_align_to(ui_dz_view_button, ui_dz_param_title_label, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_dz_view_label = lv_label_create(ui_dz_view_button);
    lv_obj_set_label_init(ui_dz_view_label, "定值查看", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_dz_view_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_dz_view_button, ui_dz_view_label);
    lv_obj_add_event_cb(ui_dz_view_button, ui_dz_param_event, LV_EVENT_ALL, NULL);


    /*-----创建定值设置菜单项-----*/
    ui_dz_set_button = lv_btn_create(ui_dz_param_title);
    lv_obj_set_button_init(ui_dz_set_button, lv_pct(100), 20);
    lv_obj_align_to(ui_dz_set_button, ui_dz_view_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_dz_set_label = lv_label_create(ui_dz_set_button);
    lv_obj_set_label_init(ui_dz_set_label, "定值修改", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_dz_set_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_dz_set_button, ui_dz_set_label);
    lv_obj_add_event_cb(ui_dz_set_button, ui_dz_param_event, LV_EVENT_ALL, NULL);

    // 将按钮添加到对象组中，使其可被输入设备导航
    lv_group_add_obj(ui_dz_param_group, ui_dz_view_button);
    lv_group_add_obj(ui_dz_param_group, ui_dz_set_button);

    lv_indev_set_group(indev, ui_dz_param_group); // 将输入设备与对象组关联

    lv_group_focus_obj(ui_dz_view_button);
}

void ui_dz_param_screen_destroy(void)
{
    if(ui_dz_param_title) lv_obj_del(ui_dz_param_title);

    // NULL screen variables
    ui_dz_param_title = NULL;
    ui_dz_param_title_label = NULL;
    ui_dz_view_button = NULL;
    ui_dz_view_label = NULL;
    ui_dz_set_button = NULL;
    ui_dz_set_label = NULL;
}
