// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_DZ_SET_H
#define UI_DZ_SET_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dz_set

typedef enum {
    DZ_VIEW_MODE,
    DZ_SET_MODE,
}dz_mode_t;
extern dz_mode_t current_dz_mode;
extern void ui_dz_set_event(lv_event_t * e);
extern void ui_dz_set_screen_init(void);
extern void ui_dz_set_screen_destroy(void);
extern lv_group_t * ui_dz_set_group;
extern lv_obj_t * ui_dz_set_title;
extern lv_obj_t * ui_dz_set_title_label;
extern lv_obj_t * ui_gy3_param_button;
extern lv_obj_t * ui_gy3_param_label;
extern lv_obj_t * ui_run_param_button;
extern lv_obj_t * ui_run_param_label;
extern lv_obj_t * ui_act_param_button;
extern lv_obj_t * ui_act_param_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

