// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "../../ui.h"
#include "../../my_file/display_init.h"
lv_group_t * ui_event_record_group = NULL;
lv_obj_t * ui_event_record_title = NULL;
lv_obj_t * ui_event_record_title_label = NULL;
lv_obj_t * ui_SOE_button = NULL;
lv_obj_t * ui_SOE_label = NULL;
lv_obj_t * ui_fault_record_button = NULL;
lv_obj_t * ui_fault_record_label = NULL;

extern lv_style_t style_option_unselected;
extern lv_style_t style_option_selected;
extern lv_style_t style_title;

// event funtions
void ui_event_record_event(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_obj_t * btn = lv_event_get_target(e);    // 获取事件目标对象（按钮）
    lv_obj_t * label = (lv_obj_t *)lv_obj_get_user_data(btn);// 从按钮的user_data中取出标签句柄
    if(label == NULL) return;

    lv_indev_t *indev = lv_win32_keypad_device_object;
    if(indev == NULL) return;

    uint32_t key;
    switch(event_code)
    {
        case LV_EVENT_FOCUSED:        // 如果事件是获得焦点
            lv_obj_remove_style(label, &style_option_unselected, 0);
            lv_obj_add_style(label, &style_option_selected, 0);
            break;
        case LV_EVENT_DEFOCUSED: // 如果事件是失去焦点
            lv_obj_remove_style(label, &style_option_selected, 0);
            lv_obj_add_style(label, &style_option_unselected, 0);
            break;
        case LV_EVENT_KEY:
            key = lv_indev_get_key(indev);
            switch(key)
            {
                case LV_KEY_ENTER:
                    if (btn == ui_SOE_button)
                    {
                        lv_indev_set_group(indev, ui_SOE_group);
                        _ui_screen_change(&ui_SOE_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SOE_screen_init);
                    }
                    else if (btn == ui_fault_record_button)
                    {
                        lv_indev_set_group(indev, ui_fault_record_group);
                        _ui_screen_change(&ui_fault_record_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_fault_record_screen_init);
                    }
                   break;
                case LV_KEY_BACKSPACE:
                    lv_indev_set_group(indev, ui_menu_main_group);
                    _ui_screen_change(&ui_menu_main_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_menu_main_screen_init);
                    break;
                default:
                    break;
                }
            break;
        default:
            break;
    }
}

// build funtions
void ui_event_record_screen_init(void)
{
    ui_event_record_title = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_event_record_title, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_event_record_group = lv_group_create(); // 创建一个新的对象组
    lv_indev_t *indev = lv_win32_keypad_device_object;

    ui_event_record_title_label = lv_label_create(ui_event_record_title);
    lv_obj_set_width(ui_event_record_title_label, lv_pct(100));
    lv_obj_set_height(ui_event_record_title_label, LV_SIZE_CONTENT);    /// 16
    lv_label_set_text(ui_event_record_title_label, "event record");
    lv_obj_set_align(ui_event_record_title_label, LV_ALIGN_TOP_MID);
    lv_obj_add_style(ui_event_record_title_label, &style_title, 0);

    /*-----创建SOE菜单项-----*/
    ui_SOE_button = lv_btn_create(ui_event_record_title);
    lv_obj_set_button_init(ui_SOE_button, lv_pct(100), 20);
    lv_obj_align_to(ui_SOE_button, ui_event_record_title_label, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_SOE_label = lv_label_create(ui_SOE_button);
    lv_obj_set_label_init(ui_SOE_label, "SOE", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_SOE_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_SOE_button, ui_SOE_label);
    lv_obj_add_event_cb(ui_SOE_button, ui_event_record_event, LV_EVENT_ALL, NULL);

    /*-----创建故障记录菜单项-----*/
    ui_fault_record_button = lv_btn_create(ui_event_record_title);
    lv_obj_set_button_init(ui_fault_record_button, lv_pct(100), 20);
    lv_obj_align_to(ui_fault_record_button, ui_SOE_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_fault_record_label = lv_label_create(ui_fault_record_button);
    lv_obj_set_label_init(ui_fault_record_label, "Fault Record", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_fault_record_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_fault_record_button, ui_fault_record_label);
    lv_obj_add_event_cb(ui_fault_record_button, ui_event_record_event, LV_EVENT_ALL, NULL);

    // 将按钮添加到对象组中，使其可被输入设备导航
    lv_group_add_obj(ui_event_record_group, ui_SOE_button);
    lv_group_add_obj(ui_event_record_group, ui_fault_record_button);

    lv_indev_set_group(indev, ui_event_record_group); // 将输入设备与对象组关联

    lv_group_focus_obj(ui_SOE_button);
}

void ui_event_record_screen_destroy(void)
{
    if(ui_event_record_title) lv_obj_del(ui_event_record_title);

    // NULL screen variables
    ui_event_record_title = NULL;
    ui_event_record_title_label = NULL;
    ui_SOE_button = NULL;
    ui_SOE_label = NULL;
    ui_fault_record_button = NULL;
    ui_fault_record_label = NULL;
}
