// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_AI_H
#define UI_AI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AI
extern void ui_AI_event(lv_event_t * e);
extern void ui_AI_screen_init(void);
extern void ui_AI_screen_destroy(void);
extern lv_group_t * ui_AI_group;
extern lv_obj_t * ui_AI_title;
extern lv_obj_t * ui_AI_title_label;
extern lv_obj_t * ui_point_AI_button;
extern lv_obj_t * ui_point_AI_label;
extern lv_obj_t * ui_all_AI_button;
extern lv_obj_t * ui_all_AI_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

