// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_ALL_AI_H
#define UI_ALL_AI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_all_ai
extern void ui_all_ai_event(lv_event_t * e);
extern void ui_all_ai_screen_init(void);
extern void ui_all_ai_screen_destroy(void);
extern lv_group_t * ui_all_ai_group;
extern lv_obj_t * ui_all_ai_title;
extern lv_obj_t * ui_all_ai_title_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

