// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_DI_H
#define UI_DI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DI
extern void ui_DI_event(lv_event_t * e);
extern void ui_DI_screen_init(void);
extern void ui_DI_screen_destroy(void);
extern lv_group_t * ui_DI_group;
extern lv_obj_t * ui_DI_title;
extern lv_obj_t * ui_DI_title_label;
extern lv_obj_t * ui_point_DI_button;
extern lv_obj_t * ui_point_DI_label;
extern lv_obj_t * ui_all_DI_button;
extern lv_obj_t * ui_all_DI_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

