// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_POINT_DI_H
#define UI_POINT_DI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_point_di
extern void ui_point_di_event(lv_event_t * e);
extern void ui_point_di_screen_init(void);
extern void ui_point_di_screen_destroy(void);
extern lv_group_t * ui_point_di_group;
extern lv_obj_t * ui_point_di_title;
extern lv_obj_t * ui_point_di_title_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

