// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_REAL_DATA_H
#define UI_REAL_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_real_data
extern void ui_real_data_screen_init(void);
extern void ui_real_data_screen_destroy(void);
extern void ui_real_data_event(lv_event_t * e);
extern lv_group_t * ui_real_data_group;
extern lv_obj_t * ui_real_data_title;
extern lv_obj_t * ui_real_data_title_label;
extern lv_obj_t * ui_AI_button;
extern lv_obj_t * ui_AI_label;
extern lv_obj_t * ui_DI_button;
extern lv_obj_t * ui_DI_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

