// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef _SQUARELINE_PROJECT_DTU_UI_H
#define _SQUARELINE_PROJECT_DTU_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////
#include "screens/main_menu/ui_menu_main.h"
#include "screens/main_menu/ui_password_check.h"
#include "screens/real_data_menu/ui_real_data.h"
#include "screens/real_data_menu/ui_AI.h"
#include "screens/real_data_menu/ui_DI.h"
#include "screens/real_data_menu/ui_point_ai.h"
#include "screens/real_data_menu/ui_all_ai.h"
#include "screens/real_data_menu/ui_point_di.h"
#include "screens/real_data_menu/ui_all_di.h"
#include "screens/event_record_menu/ui_event_record.h"
#include "screens/event_record_menu/ui_SOE.h"
#include "screens/event_record_menu/ui_fault_record.h"
#include "screens/dz_param_menu/ui_dz_param.h"
#include "screens/dz_param_menu/ui_dz_set.h"
#include "screens/dz_param_menu/ui_run_param.h"
#include "screens/dz_param_menu/ui_act_param.h"
#include "screens/dz_param_menu/ui_comrun_param.h"
#include "screens/dz_param_menu/ui_jgrun_param.h"
#include "screens/dz_param_menu/ui_comact_param.h"
#include "screens/dz_param_menu/ui_jgact_param.h"
#include "screens/dz_param_menu/ui_gy3_param.h"
#include "screens/dz_param_menu/ui_gy4_param.h"
#include "screens/com_param_menu/ui_com_param.h"
#include "screens/com_param_menu/ui_com_param2.h"
#include "screens/com_param_menu/ui_com_param3.h"
#include "screens/com_param_menu/ui_serial_param.h"
#include "screens/com_param_menu/ui_101_param.h"
#include "screens/com_param_menu/ui_104_param.h"
#include "screens/sys_maint_menu/ui_sys_maint.h"
#include "screens/clock_set_menu/ui_clock_set.h"
#include "screens/dev_manage_menu/ui_dev_manage.h"
#include "screens/dev_manage_menu/ui_dev_version.h"
#include "screens/dev_manage_menu/ui_lcd_version.h"
#include "screens/dev_manage_menu/ui_password.h"
#include "screens/dev_manage_menu/ui_ai_switch.h"
#include "screens/fa_state_menu/ui_FA_state.h"
#include "my_file/display_init.h"
#include "my_file/lcd_database.h"
///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Deng14);
LV_FONT_DECLARE(ui_font_Deng16);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
