// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "ui.h"

void switch_entry_1(lv_event_t * e)
{
	// Your code here
}
