// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "../ui.h"

lv_obj_t * ui_menu_main = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Button3 = NULL;
// event funtions

// build funtions

void ui_menu_main_screen_init(void)
{
    ui_menu_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_menu_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_menu_main);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -1);
    lv_obj_set_y(ui_Label1, -66);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "主菜单");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_AlimamaShuHeiTiBold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_menu_main);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 23);
    lv_obj_set_x(ui_Button2, 2);
    lv_obj_set_y(ui_Button2, -39);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_menu_main);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -20);
    lv_obj_set_y(ui_Button3, 44);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_menu_main_screen_destroy(void)
{
    if(ui_menu_main) lv_obj_del(ui_menu_main);

    // NULL screen variables
    ui_menu_main = NULL;
    ui_Label1 = NULL;
    ui_Button2 = NULL;
    ui_Button3 = NULL;

}
