// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "../ui.h"

lv_obj_t * ui_real_data = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions

// build funtions

void ui_real_data_screen_init(void)
{
    ui_real_data = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_real_data, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_real_data);
    lv_obj_set_width(ui_Label3, lv_pct(100));
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 3);
    lv_label_set_text(ui_Label3, "实时数据");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_myfont, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_real_data_screen_destroy(void)
{
    if(ui_real_data) lv_obj_del(ui_real_data);

    // NULL screen variables
    ui_real_data = NULL;
    ui_Label3 = NULL;

}
