// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "../../ui.h"
#include "../../my_file/display_init.h"
lv_group_t * ui_clock_set_group = NULL;
lv_obj_t * ui_clock_set_title = NULL;
lv_obj_t * ui_clock_set_title_label = NULL;
lv_obj_t * ui_terminal_time_label = NULL;

lv_obj_t * ui_clock_set_data_time_label[14];
lv_obj_t * ui_clock_set_symbol_label[4];

lv_obj_t * ui_clock_set_set_button = NULL;
lv_obj_t * ui_clock_set_set_label = NULL;

SET_STATUS clock_set_status = EMPTY;
static char real_time[40];
static lv_timer_t *clock_timer = NULL;
static char temp[2] = {0};
static int edit_idx = 0;
extern SYS_TIME64 current_time;
extern char clock_data_time[14];

extern lv_style_t style_option_unselected;
extern lv_style_t style_option_selected;
extern lv_style_t style_title;

static void clock_timer_callback(lv_timer_t *timer)
{
    if(clock_set_status == SET) return;

    clock_data_time[13]++;
    if(clock_data_time[13] > '9') {
        clock_data_time[13] = '0';
        clock_data_time[12]++;
    }
    if(clock_data_time[12] >= '6') {
        clock_data_time[12] = '0';
        clock_data_time[11]++;
    }
    if(clock_data_time[11] > '9') {
        clock_data_time[11] = '0';
        clock_data_time[10]++;
    }
    if(clock_data_time[10] >= '6') {
        clock_data_time[10] = '0';
        clock_data_time[9]++;
    }
    if(clock_data_time[9] > '9') {
        clock_data_time[9] = '0';
        clock_data_time[8]++;
    }
    if((clock_data_time[8] - '0')*10 + (clock_data_time[9] - '0') >= 24) {
        clock_data_time[8] = '0';
        clock_data_time[9] = '0';
        clock_data_time[7]++;
    }
    if(clock_data_time[7] > '9') {
        clock_data_time[7] = '0';
        clock_data_time[6]++;
    }
    if((clock_data_time[6] - '0')*10 + (clock_data_time[7] - '0') > 30) {
        clock_data_time[6] = '0';
        clock_data_time[7] = '1';
        clock_data_time[5]++;
    }
    if(clock_data_time[5] > '9') {
        clock_data_time[5] = '0';
        clock_data_time[4]++;
    }
    if((clock_data_time[4] - '0')*10 + (clock_data_time[5] - '0') > 12) {
        clock_data_time[4] = '0';
        clock_data_time[5] = '1';
        clock_data_time[3]++;
    }
    if(clock_data_time[3] > '9') {
        clock_data_time[3] = '0';
        clock_data_time[2]++;
    }
    if(clock_data_time[2] > '9') {
        clock_data_time[2] = '0';
        clock_data_time[1]++;
    }
    if(clock_data_time[1] > '9') {
        clock_data_time[1] = '0';
        clock_data_time[0]++;
    }

    upload_data_time();
    sprintf(real_time, "%d-%d-%d %d:%d:%d", current_time.year, current_time.mon, current_time.day, current_time.hour, current_time.min, current_time.sec);
    printf("%s\n",real_time);
    for (int i = 0; i < 14; i++)
    {
        sprintf(temp, "%c", clock_data_time[i]);
        lv_label_set_text(ui_clock_set_data_time_label[i], temp);
    }
}

// event funtions
void ui_clock_set_event(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_obj_t * btn = lv_event_get_target(e);    // 获取事件目标对象（按钮）
    lv_obj_t * label = (lv_obj_t *)lv_obj_get_user_data(btn);// 从按钮的user_data中取出标签句柄
    if(label == NULL) return;

    lv_indev_t *indev = lv_win32_keypad_device_object;
    if(indev == NULL) return;

    if (clock_set_status == EMPTY)
    {
        lv_obj_remove_style(label, &style_option_unselected, 0);
        lv_obj_add_style(label, &style_option_selected, 0);
        clock_set_status = NO_SET;
    }

    uint32_t key;
    switch(event_code)
    {
        case LV_EVENT_KEY:
            key = lv_indev_get_key(indev);
            switch(key)
            {
                case LV_KEY_ENTER:
                    switch(clock_set_status)
                    {
                        case NO_SET:
                            lv_obj_remove_style(label, &style_option_selected, 0);
                            lv_obj_add_style(label, &style_option_unselected, 0);
                            lv_obj_remove_style(ui_clock_set_data_time_label[0], &style_option_unselected, 0);
                            lv_obj_add_style(ui_clock_set_data_time_label[0], &style_option_selected, 0);
                            edit_idx = 0;
                            clock_set_status = SET;
                            break;
                        case SET:
                            lv_obj_remove_style(label, &style_option_unselected, 0);
                            lv_obj_add_style(label, &style_option_selected, 0);
                            lv_obj_remove_style(ui_clock_set_data_time_label[edit_idx], &style_option_selected, 0);
                            lv_obj_add_style(ui_clock_set_data_time_label[edit_idx], &style_option_unselected, 0);
                            clock_set_status = NO_SET;
                            break;
                        default:
                            clock_set_status = NO_SET;
                            break;
                    }
                    break;
                case LV_KEY_BACKSPACE:
                    clock_set_status = NO_SET;
                    upload_data_time();
                    lv_indev_set_group(indev, ui_menu_main_group);
                    _ui_screen_change(&ui_menu_main_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_menu_main_screen_init);
                    break;
                case LV_KEY_UP:
                    if (clock_set_status == NO_SET)break;
                    clock_data_time[edit_idx]++;
                    if (clock_data_time[edit_idx] > '9') clock_data_time[edit_idx] = '0';
                    sprintf(temp, "%c", clock_data_time[edit_idx]);
                    lv_label_set_text(ui_clock_set_data_time_label[edit_idx], temp);
                    break;
                case LV_KEY_DOWN:
                    if (clock_set_status == NO_SET)break;
                    clock_data_time[edit_idx]--;
                    if (clock_data_time[edit_idx] < '0') clock_data_time[edit_idx] = '9';
                    sprintf(temp, "%c", clock_data_time[edit_idx]);
                    lv_label_set_text(ui_clock_set_data_time_label[edit_idx], temp);
                    break;
                case LV_KEY_LEFT:
                    if (clock_set_status == NO_SET)break;
                    lv_obj_remove_style(ui_clock_set_data_time_label[edit_idx], &style_option_selected, 0);
                    lv_obj_add_style(ui_clock_set_data_time_label[edit_idx], &style_option_unselected, 0);
                    edit_idx--;
                    if (edit_idx < 0) edit_idx = 0;
                    lv_obj_remove_style(ui_clock_set_data_time_label[edit_idx], &style_option_unselected, 0);
                    lv_obj_add_style(ui_clock_set_data_time_label[edit_idx], &style_option_selected, 0);
                    break;
                case LV_KEY_RIGHT:
                    if (clock_set_status == NO_SET)break;
                    lv_obj_remove_style(ui_clock_set_data_time_label[edit_idx], &style_option_selected, 0);
                    lv_obj_add_style(ui_clock_set_data_time_label[edit_idx], &style_option_unselected, 0);
                    edit_idx++;
                    if (edit_idx >= 14) edit_idx = 13;
                    lv_obj_remove_style(ui_clock_set_data_time_label[edit_idx], &style_option_unselected, 0);
                    lv_obj_add_style(ui_clock_set_data_time_label[edit_idx], &style_option_selected, 0);
                    break;
                default:
                    break;
            }
        default:
            break;
    }
}

// build funtions
// build funtions
void ui_clock_set_screen_init(void)
{
    set_data_time();
    ui_clock_set_title = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_clock_set_title, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clock_set_group = lv_group_create(); // 创建一个新的对象组
    lv_indev_t *indev = lv_win32_keypad_device_object;

    ui_clock_set_title_label = lv_label_create(ui_clock_set_title);
    lv_obj_set_width(ui_clock_set_title_label, lv_pct(100));
    lv_obj_set_height(ui_clock_set_title_label, LV_SIZE_CONTENT);    /// 16
    lv_label_set_text(ui_clock_set_title_label, "Clock Set");
    lv_obj_set_align(ui_clock_set_title_label, LV_ALIGN_TOP_MID);
    lv_obj_add_style(ui_clock_set_title_label, &style_title, 0);

    /*-----创建“终端时间”便签-----*/
    ui_terminal_time_label = lv_label_create(ui_clock_set_title);
    lv_label_set_text(ui_terminal_time_label, "Terminal time");
    //lv_label_set_text(ui_terminal_time_label, "#000000 Terminal # #000000 time");
    //lv_label_set_recolor(ui_terminal_time_label, true);
    lv_obj_align_to(ui_terminal_time_label, ui_clock_set_title, LV_ALIGN_LEFT_MID, 20, -50);
    lv_obj_add_style(ui_terminal_time_label, &style_option_unselected, 0);

    // ========== 1. 年：2026 ==========
    ui_clock_set_data_time_label[0] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[0], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[0], &style_option_unselected, 0);
    lv_obj_align(ui_clock_set_data_time_label[0], LV_ALIGN_LEFT_MID, 70, 0);

    ui_clock_set_data_time_label[1] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[1], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[1], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[1], ui_clock_set_data_time_label[0], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    ui_clock_set_data_time_label[2] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[2], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[2], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[2], ui_clock_set_data_time_label[1], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    ui_clock_set_data_time_label[3] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[3], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[3], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[3], ui_clock_set_data_time_label[2], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    // ========== 2. 年-月 符号- ==========
    ui_clock_set_symbol_label[0] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_symbol_label[0], 16, 20);
    lv_label_set_text(ui_clock_set_symbol_label[0], "-");
    lv_obj_add_style(ui_clock_set_symbol_label[0], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_symbol_label[0], ui_clock_set_data_time_label[3], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    // ========== 3. 月：12 ==========
    ui_clock_set_data_time_label[4] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[4], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[4], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[4], ui_clock_set_symbol_label[0], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    ui_clock_set_data_time_label[5] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[5], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[5], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[5], ui_clock_set_data_time_label[4], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    // ========== 4. 月-日 符号- ==========
    ui_clock_set_symbol_label[1] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_symbol_label[1], 16, 20);
    lv_label_set_text(ui_clock_set_symbol_label[1], "-");
    lv_obj_add_style(ui_clock_set_symbol_label[1], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_symbol_label[1], ui_clock_set_data_time_label[5], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    // ========== 5. 日：31 ==========
    ui_clock_set_data_time_label[6] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[6], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[6], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[6], ui_clock_set_symbol_label[1], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    ui_clock_set_data_time_label[7] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[7], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[7], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[7], ui_clock_set_data_time_label[6], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    // ========== 7. 时：12 ==========
    ui_clock_set_data_time_label[8] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[8], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[8], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[8], ui_clock_set_data_time_label[1], LV_ALIGN_OUT_BOTTOM_MID, 0, 10);

    ui_clock_set_data_time_label[9] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[9], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[9], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[9], ui_clock_set_data_time_label[8], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    // ========== 8. 时-分 符号: ==========
    ui_clock_set_symbol_label[2] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_symbol_label[2], 16, 20);
    lv_label_set_text(ui_clock_set_symbol_label[2], ":");
    lv_obj_add_style(ui_clock_set_symbol_label[2], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_symbol_label[2], ui_clock_set_data_time_label[9], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    // ========== 9. 分：34 ==========
    ui_clock_set_data_time_label[10] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[10], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[10], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[10], ui_clock_set_symbol_label[2], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    ui_clock_set_data_time_label[11] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[11], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[11], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[11], ui_clock_set_data_time_label[10], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    // ========== 10. 分-秒 符号: ==========
    ui_clock_set_symbol_label[3] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_symbol_label[3], 16, 20);
    lv_label_set_text(ui_clock_set_symbol_label[3], ":");
    lv_obj_add_style(ui_clock_set_symbol_label[3], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_symbol_label[3], ui_clock_set_data_time_label[11], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    // ========== 11. 秒：56 ==========
    ui_clock_set_data_time_label[12] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[12], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[12], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[12], ui_clock_set_symbol_label[3], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    ui_clock_set_data_time_label[13] = lv_label_create(ui_clock_set_title);
    lv_obj_set_size(ui_clock_set_data_time_label[13], 16, 20);
    lv_obj_add_style(ui_clock_set_data_time_label[13], &style_option_unselected, 0);
    lv_obj_align_to(ui_clock_set_data_time_label[13], ui_clock_set_data_time_label[12], LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    for (size_t i = 0; i < sizeof(clock_data_time); i++)
    {
        sprintf(temp, "%c", clock_data_time[i]);
        lv_label_set_text(ui_clock_set_data_time_label[i], temp);
    }

    /*-----创建设置按键-----*/
    ui_clock_set_set_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_set_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_set_button, ui_clock_set_title, LV_ALIGN_CENTER, 0, 60);
    ui_clock_set_set_label = lv_label_create(ui_clock_set_set_button);
    lv_obj_set_label_init(ui_clock_set_set_label, "set", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_set_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_set_button, ui_clock_set_set_label);
    lv_obj_add_event_cb(ui_clock_set_set_button, ui_clock_set_event, LV_EVENT_ALL, NULL);

    // 将按钮添加到对象组中，使其可被输入设备导航
    lv_group_add_obj(ui_clock_set_group, ui_clock_set_set_button);

    lv_indev_set_group(indev, ui_clock_set_group); // 将输入设备与对象组关联

    lv_group_focus_obj(ui_clock_set_set_button);

    /*-----创建定时器-----*/
    clock_timer = lv_timer_create(clock_timer_callback, 1000, NULL);
    //lv_timer_pause(clock_timer)	//暂停定时器，后面可以用 lv_timer_resume() 恢复
    //lv_timer_del(clock_timer);
}

void ui_clock_set_screen_destroy(void)
{
    if(clock_timer) lv_timer_del(clock_timer);
    if(ui_clock_set_title) lv_obj_del(ui_clock_set_title);

    // NULL screen variables
    ui_clock_set_group = NULL;
    ui_clock_set_title = NULL;
    ui_clock_set_title_label = NULL;
    ui_terminal_time_label = NULL;
    for(int i = 0; i < 14; i++)
    {
        ui_clock_set_data_time_label[i] = NULL;
    }
    for(int i = 0; i < 4; i++)
    {
        ui_clock_set_symbol_label[i] = NULL;
    }
    ui_clock_set_set_button = NULL;
    ui_clock_set_set_label = NULL;
}
