// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "../../ui.h"
#include "../../my_file/display_init.h"
lv_group_t * ui_clock_set_group = NULL;
lv_obj_t * ui_clock_set_title = NULL;
lv_obj_t * ui_clock_set_title_label = NULL;
lv_obj_t * ui_terminal_time_label = NULL;

lv_obj_t * ui_clock_set_year_label = NULL;
lv_obj_t * ui_clock_set_year1_button = NULL;
lv_obj_t * ui_clock_set_year1_label = NULL;
lv_obj_t * ui_clock_set_year2_button = NULL;
lv_obj_t * ui_clock_set_year2_label = NULL;
lv_obj_t * ui_clock_set_month1_button = NULL;
lv_obj_t * ui_clock_set_month1_label = NULL;
lv_obj_t * ui_clock_set_month2_button = NULL;
lv_obj_t * ui_clock_set_month2_label = NULL;
lv_obj_t * ui_clock_set_day1_button = NULL;
lv_obj_t * ui_clock_set_day1_label = NULL;
lv_obj_t * ui_clock_set_day2_button = NULL;
lv_obj_t * ui_clock_set_day2_label = NULL;
lv_obj_t * ui_clock_set_hour1_button = NULL;
lv_obj_t * ui_clock_set_hour1_label = NULL;
lv_obj_t * ui_clock_set_hour2_button = NULL;
lv_obj_t * ui_clock_set_hour2_label = NULL;
lv_obj_t * ui_clock_set_min1_button = NULL;
lv_obj_t * ui_clock_set_min1_label = NULL;
lv_obj_t * ui_clock_set_min2_button = NULL;
lv_obj_t * ui_clock_set_min2_label = NULL;
lv_obj_t * ui_clock_set_sec1_button = NULL;
lv_obj_t * ui_clock_set_sec1_label = NULL;
lv_obj_t * ui_clock_set_sec2_button = NULL;
lv_obj_t * ui_clock_set_sec2_label = NULL;

lv_obj_t * ui_clock_set_set_button = NULL;
lv_obj_t * ui_clock_set_set_label = NULL;

SYS_TIME64 current_time = {2026, 1, 1, 0, 0, 0, 0};

extern lv_style_t style_option_unselected;
extern lv_style_t style_option_selected;
extern lv_style_t style_title;

// event funtions
void ui_clock_set_event(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_obj_t * btn = lv_event_get_target(e);    // 获取事件目标对象（按钮）
    lv_obj_t * label = (lv_obj_t *)lv_obj_get_user_data(btn);// 从按钮的user_data中取出标签句柄
    if(label == NULL) return;

    lv_indev_t *indev = lv_win32_keypad_device_object;
    if(indev == NULL) return;

    uint32_t key;
    switch(event_code)
    {
        case LV_EVENT_FOCUSED:        // 如果事件是获得焦点
            lv_obj_remove_style(label, &style_option_unselected, 0);
            lv_obj_add_style(label, &style_option_selected, 0);
            break;
        case LV_EVENT_DEFOCUSED: // 如果事件是失去焦点
            lv_obj_remove_style(label, &style_option_selected, 0);
            lv_obj_add_style(label, &style_option_unselected, 0);
            break;
        case LV_EVENT_KEY:
            key = lv_indev_get_key(indev);
            switch(key)
            {
                case LV_KEY_ENTER:
                    break;
                case LV_KEY_BACKSPACE:
                    lv_indev_set_group(indev, ui_menu_main_group);
                    _ui_screen_change(&ui_menu_main_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_menu_main_screen_init);
                    break;
                default:
                    break;
                }
            break;
        default:
            break;
    }
}

// build funtions
void ui_clock_set_screen_init(void)
{
    ui_clock_set_title = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_clock_set_title, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clock_set_group = lv_group_create(); // 创建一个新的对象组
    lv_indev_t *indev = lv_win32_keypad_device_object;

    ui_clock_set_title_label = lv_label_create(ui_clock_set_title);
    lv_obj_set_width(ui_clock_set_title_label, lv_pct(100));
    lv_obj_set_height(ui_clock_set_title_label, LV_SIZE_CONTENT);    /// 16
    lv_label_set_text(ui_clock_set_title_label, "Clock Set");
    lv_obj_set_align(ui_clock_set_title_label, LV_ALIGN_TOP_MID);
    lv_obj_add_style(ui_clock_set_title_label, &style_title, 0);

    /*-----创建“终端时间”便签-----*/
    ui_terminal_time_label = lv_label_create(ui_clock_set_title);
    lv_label_set_text(ui_terminal_time_label, "Terminal time");
    lv_obj_align_to(ui_terminal_time_label, ui_clock_set_title, LV_ALIGN_LEFT_MID, 0, -50);
    lv_obj_add_style(ui_terminal_time_label, &style_option_unselected, 0);

    /*-----创建“年”按键-----*/
    ui_clock_set_year_label = lv_label_create(ui_clock_set_title);
    lv_label_set_text(ui_clock_set_year_label, "20");
    lv_obj_align_to(ui_clock_set_year_label, ui_terminal_time_label, LV_ALIGN_OUT_BOTTOM_LEFT, 0, 0);
    lv_obj_add_style(ui_clock_set_year_label, &style_option_unselected, 0);

    ui_clock_set_year1_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_year1_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_year1_button, ui_clock_set_year_label, LV_ALIGN_OUT_RIGHT_MID, 0, 4);
    ui_clock_set_year1_label = lv_label_create(ui_clock_set_year1_button);
    lv_obj_set_label_init(ui_clock_set_year1_label, "2", LV_ALIGN_CENTER);

    lv_obj_add_style(ui_clock_set_year1_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_year1_button, ui_clock_set_year1_label);
    lv_obj_add_event_cb(ui_clock_set_year1_button, ui_clock_set_event, LV_EVENT_ALL, NULL);
    ui_clock_set_year2_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_year2_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_year2_button, ui_clock_set_year1_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_year2_label = lv_label_create(ui_clock_set_year2_button);
    lv_obj_set_label_init(ui_clock_set_year2_label, "6", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_year2_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_year2_button, ui_clock_set_year2_label);
    lv_obj_add_event_cb(ui_clock_set_year2_button, ui_clock_set_event, LV_EVENT_ALL, NULL);

    /*-----创建“月”按键-----*/
    ui_clock_set_month1_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_month_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_month_button, ui_clock_set_year2_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_month1_label = lv_label_create(ui_clock_set_month_button);
    lv_obj_set_label_init(ui_clock_set_month_label, "month", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_month_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_month_button, ui_clock_set_month_label);
    lv_obj_add_event_cb(ui_clock_set_month_button, ui_clock_set_event, LV_EVENT_ALL, NULL);
    ui_clock_set_month2_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_month2_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_month2_button, ui_clock_set_year2_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_month2_label = lv_label_create(ui_clock_set_month2_button);
    lv_obj_set_label_init(ui_clock_set_month2_label, "month", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_month2_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_month2_button, ui_clock_set_month2_label);
    lv_obj_add_event_cb(ui_clock_set_month2_button, ui_clock_set_event, LV_EVENT_ALL, NULL);

    /*-----创建“日”按键-----*/
    ui_clock_set_day_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_day_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_day_button, ui_clock_set_month_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_day_label = lv_label_create(ui_clock_set_day_button);
    lv_obj_set_label_init(ui_clock_set_day_label, "day", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_day_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_day_button, ui_clock_set_day_label);
    lv_obj_add_event_cb(ui_clock_set_day_button, ui_clock_set_event, LV_EVENT_ALL, NULL);
    ui_clock_set_day_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_day_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_day_button, ui_clock_set_month_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_day_label = lv_label_create(ui_clock_set_day_button);
    lv_obj_set_label_init(ui_clock_set_day_label, "day", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_day_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_day_button, ui_clock_set_day_label);
    lv_obj_add_event_cb(ui_clock_set_day_button, ui_clock_set_event, LV_EVENT_ALL, NULL);

    /*-----创建“时”按键-----*/
    ui_clock_set_hour_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_hour_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_hour_button, ui_clock_set_day_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_hour_label = lv_label_create(ui_clock_set_hour_button);
    lv_obj_set_label_init(ui_clock_set_hour_label, "hour", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_hour_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_hour_button, ui_clock_set_hour_label);
    lv_obj_add_event_cb(ui_clock_set_hour_button, ui_clock_set_event, LV_EVENT_ALL, NULL);
    ui_clock_set_hour_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_hour_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_hour_button, ui_clock_set_day_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_hour_label = lv_label_create(ui_clock_set_hour_button);
    lv_obj_set_label_init(ui_clock_set_hour_label, "hour", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_hour_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_hour_button, ui_clock_set_hour_label);
    lv_obj_add_event_cb(ui_clock_set_hour_button, ui_clock_set_event, LV_EVENT_ALL, NULL);

    /*-----创建“分”按键-----*/
    ui_clock_set_min_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_min_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_min_button, ui_clock_set_hour_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_min_label = lv_label_create(ui_clock_set_min_button);
    lv_obj_set_label_init(ui_clock_set_min_label, "min", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_min_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_min_button, ui_clock_set_min_label);
    lv_obj_add_event_cb(ui_clock_set_min_button, ui_clock_set_event, LV_EVENT_ALL, NULL);
    ui_clock_set_min_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_min_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_min_button, ui_clock_set_hour_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_min_label = lv_label_create(ui_clock_set_min_button);
    lv_obj_set_label_init(ui_clock_set_min_label, "min", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_min_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_min_button, ui_clock_set_min_label);
    lv_obj_add_event_cb(ui_clock_set_min_button, ui_clock_set_event, LV_EVENT_ALL, NULL);

    /*-----创建“秒”按键-----*/
    ui_clock_set_sec_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_sec_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_sec_button, ui_clock_set_min_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_sec_label = lv_label_create(ui_clock_set_sec_button);
    lv_obj_set_label_init(ui_clock_set_sec_label, "sec", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_sec_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_sec_button, ui_clock_set_sec_label);
    lv_obj_add_event_cb(ui_clock_set_sec_button, ui_clock_set_event, LV_EVENT_ALL, NULL);
    ui_clock_set_sec_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_sec_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_sec_button, ui_clock_set_min_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_sec_label = lv_label_create(ui_clock_set_sec_button);
    lv_obj_set_label_init(ui_clock_set_sec_label, "sec", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_sec_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_sec_button, ui_clock_set_sec_label);
    lv_obj_add_event_cb(ui_clock_set_sec_button, ui_clock_set_event, LV_EVENT_ALL, NULL);

    /*-----创建设置按键-----*/
    ui_clock_set_set_button = lv_btn_create(ui_clock_set_title);
    lv_obj_set_button_init(ui_clock_set_set_button, lv_pct(100), 20);
    lv_obj_align_to(ui_clock_set_set_button, ui_terminal_time_label, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_clock_set_set_label = lv_label_create(ui_clock_set_set_button);
    lv_obj_set_label_init(ui_clock_set_set_label, "set", LV_ALIGN_CENTER);
    lv_obj_add_style(ui_clock_set_set_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_clock_set_set_button, ui_clock_set_set_label);
    lv_obj_add_event_cb(ui_clock_set_set_button, ui_clock_set_event, LV_EVENT_ALL, NULL);

    // 将按钮添加到对象组中，使其可被输入设备导航
    lv_group_add_obj(ui_event_record_group, ui_clock_set_set_button);

    lv_indev_set_group(indev, ui_event_record_group); // 将输入设备与对象组关联

    lv_group_focus_obj(ui_clock_set_set_button);
}

void ui_clock_set_screen_destroy(void)
{
    if(ui_clock_set_title) lv_obj_del(ui_clock_set_title);

    // NULL screen variables
    ui_clock_set_title = NULL;
    ui_clock_set_title_label = NULL;
    ui_terminal_time_label = NULL;
    ui_clock_set_set_button = NULL;
    ui_clock_set_set_label = NULL;
}
