// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "../../ui.h"
#include "../../my_file/display_init.h"
lv_group_t * ui_ai_switch_group = NULL;
lv_obj_t * ui_ai_switch_title = NULL;
lv_obj_t * ui_ai_switch_title_label = NULL;
lv_obj_t * ui_ai_switch_ais_button = NULL;
lv_obj_t * ui_ai_switch_ais_label = NULL;
lv_obj_t * ui_ai_switch_ais_label2 = NULL;

static int ui_ai_switch_ais_label2_index = 1;

extern lv_style_t style_option_unselected;
extern lv_style_t style_option_selected;
extern lv_style_t style_title;

// event funtions
void ui_ai_switch_event(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_obj_t * btn = lv_event_get_target(e);    // 获取事件目标对象（按钮）
    if(btn == NULL) return;
    lv_obj_t * label = (lv_obj_t *)lv_obj_get_user_data(btn);// 从按钮的user_data中取出标签句柄
    if(label == NULL) return;
    lv_group_t *group = lv_obj_get_group(btn);  // 获取按钮所属的组
    if(group == NULL) return;

    lv_indev_t *indev = lv_win32_keypad_device_object;
    if(indev == NULL) return;

    uint32_t key;
    switch(event_code)
    {
        case LV_EVENT_FOCUSED:        // 如果事件是获得焦点
            lv_obj_remove_style(label, &style_option_unselected, 0);
            lv_obj_add_style(label, &style_option_selected, 0);
            break;
        case LV_EVENT_DEFOCUSED: // 如果事件是失去焦点
            lv_obj_remove_style(label, &style_option_selected, 0);
            lv_obj_add_style(label, &style_option_unselected, 0);
            break;
        case LV_EVENT_KEY:
            key = lv_indev_get_key(indev);
            switch(key)
            {
                case LV_KEY_ENTER:
                    if(btn == ui_ai_switch_ais_button && ui_display.edit_state == UNEDIT_STATE) {
                        lv_obj_remove_style(ui_ai_switch_ais_label2, &style_option_unselected, 0);
                        lv_obj_add_style(ui_ai_switch_ais_label2, &style_option_selected, 0);
                        ui_display.edit_state = EDIT_STATE;
                        break;
                    }
                    if (btn == ui_ai_switch_ais_button && ui_display.edit_state == EDIT_STATE)
                    {
                        lv_obj_remove_style(ui_ai_switch_ais_label2, &style_option_selected, 0);
                        lv_obj_add_style(ui_ai_switch_ais_label2, &style_option_unselected, 0);
                        ui_display.edit_state = UNEDIT_STATE;
                        break;
                    }
                    break;
                case LV_KEY_BACKSPACE:
                    if (btn == ui_ai_switch_ais_button && ui_display.edit_state == UNEDIT_STATE)
                    {
                        lv_indev_set_group(indev, ui_dev_manage_group);
                        _ui_screen_change(&ui_dev_manage_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dev_manage_screen_init);
                        break;
                    }
                    if (btn == ui_ai_switch_ais_button && ui_display.edit_state == EDIT_STATE)
                    {
                        lv_obj_remove_style(ui_ai_switch_ais_label2, &style_option_selected, 0);
                        lv_obj_add_style(ui_ai_switch_ais_label2, &style_option_unselected, 0);
                        ui_display.edit_state = UNEDIT_STATE;
                        break;
                    }
                   break;
                case LV_KEY_UP:
                    if(group != NULL && ui_display.edit_state == UNEDIT_STATE) {
                        lv_group_focus_prev(group);
                    }
                    if (btn == ui_ai_switch_ais_button && ui_display.edit_state == EDIT_STATE)
                    {
                        if (ui_ai_switch_ais_label2_index == 1)
                        {
                            ui_ai_switch_ais_label2_index = 2;
                            lv_label_set_text(ui_ai_switch_ais_label2, "二次值");
                        }else
                        {
                            ui_ai_switch_ais_label2_index = 1;
                            lv_label_set_text(ui_ai_switch_ais_label2, "一次值");
                        }
                    }
                    break;
                case LV_KEY_DOWN:
                    if(group != NULL && ui_display.edit_state == UNEDIT_STATE) {
                        lv_group_focus_next(group);
                    }
                    if (btn == ui_ai_switch_ais_button && ui_display.edit_state == EDIT_STATE)
                    {
                        if (ui_ai_switch_ais_label2_index == 1)
                        {
                            ui_ai_switch_ais_label2_index = 2;
                            lv_label_set_text(ui_ai_switch_ais_label2, "二次值");
                        }else
                        {
                            ui_ai_switch_ais_label2_index = 1;
                            lv_label_set_text(ui_ai_switch_ais_label2, "一次值");
                        }
                    }
                    break;
                default:
                    break;
            }
            break;
        default:
            break;
    }
}

// build funtions
void ui_ai_switch_screen_init(void)
{
    ui_ai_switch_title = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ai_switch_title, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ai_switch_group = lv_group_create(); // 创建一个新的对象组
    lv_indev_t *indev = lv_win32_keypad_device_object;

    ui_ai_switch_title_label = lv_label_create(ui_ai_switch_title);
    lv_obj_set_width(ui_ai_switch_title_label, lv_pct(100));
    lv_obj_set_height(ui_ai_switch_title_label, LV_SIZE_CONTENT);    /// 16
    lv_label_set_text(ui_ai_switch_title_label, "遥测切换");
    lv_obj_set_align(ui_ai_switch_title_label, LV_ALIGN_TOP_MID);
    lv_obj_add_style(ui_ai_switch_title_label, &style_title, 0);

    /*-----创建遥测一二次值菜单项-----*/
    ui_ai_switch_ais_button = lv_btn_create(ui_ai_switch_title);
    lv_obj_set_button_init(ui_ai_switch_ais_button, 100, 20);
    lv_obj_align_to(ui_ai_switch_ais_button, ui_ai_switch_title_label, LV_ALIGN_OUT_BOTTOM_LEFT, 2, 4);
    ui_ai_switch_ais_label = lv_label_create(ui_ai_switch_ais_button);
    lv_obj_set_label_init(ui_ai_switch_ais_label, "遥测一二次值", LV_ALIGN_LEFT_MID);
    lv_obj_add_style(ui_ai_switch_ais_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_ai_switch_ais_button, ui_ai_switch_ais_label);
    lv_obj_add_event_cb(ui_ai_switch_ais_button, ui_ai_switch_event, LV_EVENT_ALL, NULL);

    ui_ai_switch_ais_label2 = lv_label_create(ui_ai_switch_title);
    lv_obj_set_label_init(ui_ai_switch_ais_label2, "一次值", LV_ALIGN_LEFT_MID);
    lv_obj_add_style(ui_ai_switch_ais_label2, &style_option_unselected, 0);
    lv_obj_align_to(ui_ai_switch_ais_label2, ui_ai_switch_ais_button, LV_ALIGN_OUT_RIGHT_MID, 10, 0);

    // 将按钮添加到对象组中，使其可被输入设备导航
    lv_group_add_obj(ui_ai_switch_group, ui_ai_switch_ais_button);

    lv_indev_set_group(indev, ui_ai_switch_group); // 将输入设备与对象组关联

    lv_group_focus_obj(ui_ai_switch_ais_button);
}

void ui_ai_switch_screen_destroy(void)
{
    if(ui_ai_switch_title) lv_obj_del(ui_ai_switch_title);

    // NULL screen variables
    ui_ai_switch_title = NULL;
    ui_ai_switch_title_label = NULL;
    ui_ai_switch_ais_button = NULL;
    ui_ai_switch_ais_label = NULL;
    ui_ai_switch_ais_label2 = NULL;
}
