// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_DEV_MANAGE_H
#define UI_DEV_MANAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dev_manage
extern void ui_dev_manage_event(lv_event_t * e);
extern void ui_dev_manage_screen_init(void);
extern void ui_dev_manage_screen_destroy(void);
extern lv_group_t * ui_dev_manage_group;
extern lv_obj_t * ui_dev_manage_title;
extern lv_obj_t * ui_dev_manage_title_label;
extern lv_obj_t * ui_dev_version_button;
extern lv_obj_t * ui_dev_version_label;
extern lv_obj_t * ui_lcd_version_button;
extern lv_obj_t * ui_lcd_version_label;
extern lv_obj_t * ui_password_button;
extern lv_obj_t * ui_password_label;
extern lv_obj_t * ui_ai_switch_button;
extern lv_obj_t * ui_ai_switch_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

