// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_LCD_VERSION_H
#define UI_LCD_VERSION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_lcd_version
extern void ui_lcd_version_event(lv_event_t * e);
extern void ui_lcd_version_screen_init(void);
extern void ui_lcd_version_screen_destroy(void);
extern lv_group_t * ui_lcd_version_group;
extern lv_obj_t * ui_lcd_version_title;
extern lv_obj_t * ui_lcd_version_title_label;
extern lv_obj_t * ui_lcd_version_ver_button;
extern lv_obj_t * ui_lcd_version_ver_label;
extern lv_obj_t * ui_lcd_version_ver_label2;
extern lv_obj_t * ui_lcd_version_date_button;
extern lv_obj_t * ui_lcd_version_date_label;
extern lv_obj_t * ui_lcd_version_date_label2;
extern lv_obj_t * ui_lcd_version_crc_button;
extern lv_obj_t * ui_lcd_version_crc_label;
extern lv_obj_t * ui_lcd_version_crc_label2;
extern lv_obj_t * ui_lcd_version_desc_button;
extern lv_obj_t * ui_lcd_version_desc_label;
extern lv_obj_t * ui_lcd_version_desc_label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

