// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#include "../../ui.h"
#include "../../my_file/display_init.h"
lv_group_t * ui_lcd_version_group = NULL;
lv_obj_t * ui_lcd_version_title = NULL;
lv_obj_t * ui_lcd_version_title_label = NULL;
lv_obj_t * ui_lcd_version_ver_button = NULL;
lv_obj_t * ui_lcd_version_ver_label = NULL;
lv_obj_t * ui_lcd_version_ver_label2 = NULL;
lv_obj_t * ui_lcd_version_date_button = NULL;
lv_obj_t * ui_lcd_version_date_label = NULL;
lv_obj_t * ui_lcd_version_date_label2 = NULL;
lv_obj_t * ui_lcd_version_crc_button = NULL;
lv_obj_t * ui_lcd_version_crc_label = NULL;
lv_obj_t * ui_lcd_version_crc_label2 = NULL;
lv_obj_t * ui_lcd_version_desc_button = NULL;
lv_obj_t * ui_lcd_version_desc_label = NULL;
lv_obj_t * ui_lcd_version_desc_label2 = NULL;

extern lv_style_t style_option_unselected;
extern lv_style_t style_option_selected;
extern lv_style_t style_title;

// event funtions
void ui_lcd_version_event(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    lv_obj_t * btn = lv_event_get_target(e);    // 获取事件目标对象（按钮）
    if(btn == NULL) return;
    lv_obj_t * label = (lv_obj_t *)lv_obj_get_user_data(btn);// 从按钮的user_data中取出标签句柄
    if(label == NULL) return;
    lv_group_t *group = lv_obj_get_group(btn);  // 获取按钮所属的组
    if(group == NULL) return;

    lv_indev_t *indev = lv_win32_keypad_device_object;
    if(indev == NULL) return;

    uint32_t key;
    switch(event_code)
    {
        case LV_EVENT_FOCUSED:        // 如果事件是获得焦点
            lv_obj_remove_style(label, &style_option_unselected, 0);
            lv_obj_add_style(label, &style_option_selected, 0);
            break;
        case LV_EVENT_DEFOCUSED: // 如果事件是失去焦点
            lv_obj_remove_style(label, &style_option_selected, 0);
            lv_obj_add_style(label, &style_option_unselected, 0);
            break;
        case LV_EVENT_KEY:
            key = lv_indev_get_key(indev);
            switch(key)
            {
                case LV_KEY_ENTER:
                    break;
                case LV_KEY_BACKSPACE:
                    lv_indev_set_group(indev, ui_dev_manage_group);
                    _ui_screen_change(&ui_dev_manage_title, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dev_manage_screen_init);
                    break;
                case LV_KEY_UP:
                    if(group != NULL && ui_display.edit_state == UNEDIT_STATE) {
                        lv_group_focus_prev(group);
                    }
                    break;
                case LV_KEY_DOWN:
                    if(group != NULL && ui_display.edit_state == UNEDIT_STATE) {
                        lv_group_focus_next(group);
                    }
                    break;
                default:
                    break;
            }
            break;
        default:
            break;
    }
}

// build funtions
void ui_lcd_version_screen_init(void)
{
    ui_lcd_version_title = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_lcd_version_title, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lcd_version_group = lv_group_create(); // 创建一个新的对象组
    lv_indev_t *indev = lv_win32_keypad_device_object;

    ui_lcd_version_title_label = lv_label_create(ui_lcd_version_title);
    lv_obj_set_width(ui_lcd_version_title_label, lv_pct(100));
    lv_obj_set_height(ui_lcd_version_title_label, LV_SIZE_CONTENT);    /// 16
    lv_label_set_text(ui_lcd_version_title_label, "液晶版本");
    lv_obj_set_align(ui_lcd_version_title_label, LV_ALIGN_TOP_MID);
    lv_obj_add_style(ui_lcd_version_title_label, &style_title, 0);
    
    /*-----创建版本菜单项-----*/
    ui_lcd_version_ver_button = lv_btn_create(ui_lcd_version_title);
    lv_obj_set_button_init(ui_lcd_version_ver_button, 50, 20);
    lv_obj_align_to(ui_lcd_version_ver_button, ui_lcd_version_title_label, LV_ALIGN_OUT_BOTTOM_LEFT, 2, 4);
    ui_lcd_version_ver_label = lv_label_create(ui_lcd_version_ver_button);
    lv_obj_set_label_init(ui_lcd_version_ver_label, "版本", LV_ALIGN_LEFT_MID);
    lv_obj_add_style(ui_lcd_version_ver_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_lcd_version_ver_button, ui_lcd_version_ver_label);
    lv_obj_add_event_cb(ui_lcd_version_ver_button, ui_lcd_version_event, LV_EVENT_ALL, NULL);

    ui_lcd_version_ver_label2 = lv_label_create(ui_lcd_version_title);
    lv_obj_set_label_init(ui_lcd_version_ver_label2, "ZD30", LV_ALIGN_LEFT_MID);
    lv_obj_add_style(ui_lcd_version_ver_label2, &style_option_unselected, 0);
    lv_obj_align_to(ui_lcd_version_ver_label2, ui_lcd_version_ver_button, LV_ALIGN_OUT_RIGHT_MID, 10, 0);

    /*-----创建日期菜单项-----*/
    ui_lcd_version_date_button = lv_btn_create(ui_lcd_version_title);
    lv_obj_set_button_init(ui_lcd_version_date_button, 50, 20);
    lv_obj_align_to(ui_lcd_version_date_button, ui_lcd_version_ver_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_lcd_version_date_label = lv_label_create(ui_lcd_version_date_button);
    lv_obj_set_label_init(ui_lcd_version_date_label, "日期", LV_ALIGN_LEFT_MID);
    lv_obj_add_style(ui_lcd_version_date_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_lcd_version_date_button, ui_lcd_version_date_label);
    lv_obj_add_event_cb(ui_lcd_version_date_button, ui_lcd_version_event, LV_EVENT_ALL, NULL);

    ui_lcd_version_date_label2 = lv_label_create(ui_lcd_version_title);
    lv_obj_set_label_init(ui_lcd_version_date_label2, "2026-02-02", LV_ALIGN_LEFT_MID);
    lv_obj_add_style(ui_lcd_version_date_label2, &style_option_unselected, 0);
    lv_obj_align_to(ui_lcd_version_date_label2, ui_lcd_version_date_button, LV_ALIGN_OUT_RIGHT_MID, 10, 0);

    /*-----创建CRC菜单项-----*/
    ui_lcd_version_crc_button = lv_btn_create(ui_lcd_version_title);
    lv_obj_set_button_init(ui_lcd_version_crc_button, 50, 20);
    lv_obj_align_to(ui_lcd_version_crc_button, ui_lcd_version_date_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_lcd_version_crc_label = lv_label_create(ui_lcd_version_crc_button);
    lv_obj_set_label_init(ui_lcd_version_crc_label, "CRC", LV_ALIGN_LEFT_MID);
    lv_obj_add_style(ui_lcd_version_crc_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_lcd_version_crc_button, ui_lcd_version_crc_label);
    lv_obj_add_event_cb(ui_lcd_version_crc_button, ui_lcd_version_event, LV_EVENT_ALL, NULL);

    ui_lcd_version_crc_label2 = lv_label_create(ui_lcd_version_title);
    lv_obj_set_label_init(ui_lcd_version_crc_label2, "2B2B", LV_ALIGN_LEFT_MID);
    lv_obj_add_style(ui_lcd_version_crc_label2, &style_option_unselected, 0);
    lv_obj_align_to(ui_lcd_version_crc_label2, ui_lcd_version_crc_button, LV_ALIGN_OUT_RIGHT_MID, 10, 0);

    /*-----创建说明菜单项-----*/
    ui_lcd_version_desc_button = lv_btn_create(ui_lcd_version_title);
    lv_obj_set_button_init(ui_lcd_version_desc_button, 50, 20);
    lv_obj_align_to(ui_lcd_version_desc_button, ui_lcd_version_crc_button, LV_ALIGN_OUT_BOTTOM_MID, 0, 4);
    ui_lcd_version_desc_label = lv_label_create(ui_lcd_version_desc_button);
    lv_obj_set_label_init(ui_lcd_version_desc_label, "说明", LV_ALIGN_LEFT_MID);
    lv_obj_add_style(ui_lcd_version_desc_label, &style_option_unselected, 0);
    lv_obj_set_user_data(ui_lcd_version_desc_button, ui_lcd_version_desc_label);
    lv_obj_add_event_cb(ui_lcd_version_desc_button, ui_lcd_version_event, LV_EVENT_ALL, NULL);

    ui_lcd_version_desc_label2 = lv_label_create(ui_lcd_version_title);
    lv_obj_set_label_init(ui_lcd_version_desc_label2, "SH-DTU-LCD", LV_ALIGN_LEFT_MID);
    lv_obj_add_style(ui_lcd_version_desc_label2, &style_option_unselected, 0);
    lv_obj_align_to(ui_lcd_version_desc_label2, ui_lcd_version_desc_button, LV_ALIGN_OUT_RIGHT_MID, 10, 0);

    // 将按钮添加到对象组中，使其可被输入设备导航
    lv_group_add_obj(ui_lcd_version_group, ui_lcd_version_ver_button);
    lv_group_add_obj(ui_lcd_version_group, ui_lcd_version_date_button);
    lv_group_add_obj(ui_lcd_version_group, ui_lcd_version_crc_button);
    lv_group_add_obj(ui_lcd_version_group, ui_lcd_version_desc_button);

    lv_indev_set_group(indev, ui_lcd_version_group); // 将输入设备与对象组关联

    lv_group_focus_obj(ui_lcd_version_ver_button);
}

void ui_lcd_version_screen_destroy(void)
{
    if(ui_lcd_version_title) lv_obj_del(ui_lcd_version_title);

    // NULL screen variables
    ui_lcd_version_title = NULL;
    ui_lcd_version_title_label = NULL;
    ui_lcd_version_ver_button = NULL;
    ui_lcd_version_ver_label = NULL;
    ui_lcd_version_ver_label2 = NULL;
    ui_lcd_version_date_button = NULL;
    ui_lcd_version_date_label = NULL;
    ui_lcd_version_date_label2 = NULL;
    ui_lcd_version_crc_button = NULL;
    ui_lcd_version_crc_label = NULL;
    ui_lcd_version_crc_label2 = NULL;
    ui_lcd_version_desc_button = NULL;
    ui_lcd_version_desc_label = NULL;
    ui_lcd_version_desc_label2 = NULL;
}
