// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_PASSWORD_H
#define UI_PASSWORD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_password
extern void ui_password_event(lv_event_t * e);
extern void ui_password_screen_init(void);
extern void ui_password_screen_destroy(void);
extern lv_group_t * ui_password_group;
extern lv_obj_t * ui_password_title;
extern lv_obj_t * ui_password_title_label;
extern lv_obj_t * ui_password_old_button;
extern lv_obj_t * ui_password_old_label;
extern lv_obj_t * ui_password_new_button;
extern lv_obj_t * ui_password_new_label;
extern lv_obj_t * ui_password_reset_button;
extern lv_obj_t * ui_password_reset_label;
extern lv_obj_t * password_old_label[4];
extern lv_obj_t * password_new_label[4];
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

