// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_DZ_PARAM_H
#define UI_DZ_PARAM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dz_param
extern lv_group_t * ui_dz_param_group;
extern void ui_dz_param_event(lv_event_t * e);
extern void ui_dz_param_screen_init(void);
extern void ui_dz_param_screen_destroy(void);
extern lv_group_t * ui_dz_param_group;
extern lv_obj_t * ui_dz_param_title;
extern lv_obj_t * ui_dz_param_title_label;
extern lv_obj_t * ui_dz_view_button;
extern lv_obj_t * ui_dz_view_label;
extern lv_obj_t * ui_dz_set_button;
extern lv_obj_t * ui_dz_set_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

