// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_DO_H
#define UI_DO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DO
extern lv_group_t * ui_DO_group;
extern void ui_DO_event(lv_event_t * e);
extern void ui_DO_screen_init(void);
extern void ui_DO_screen_destroy(void);
extern lv_group_t * ui_DO_group;
extern lv_obj_t * ui_DO_title;
extern lv_obj_t * ui_point_DO_button;
extern lv_obj_t * ui_point_DO_label;
extern lv_obj_t * ui_all_DO_button;
extern lv_obj_t * ui_all_DO_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

