// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project_DTU

#ifndef UI_FA_STATE_H
#define UI_FA_STATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FA_state
extern void ui_FA_state_event(lv_event_t * e);
extern void ui_FA_state_screen_init(void);
extern void ui_FA_state_screen_destroy(void);
extern lv_group_t * ui_FA_state_group;
extern lv_obj_t * ui_FA_state_title;
extern lv_obj_t * ui_FA_state_title_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

